### PR TITLE
close #135 add acleda support to bookmeplus

### LINKED ISSUE #135: Add ACLEDA support to BookMe+

### PR DESCRIPTION
**Pull request by theachoem**
## Intro
- ACLEDA was already integrated before, this PR is for review and refactor to support latest ACLEDA and [documents](https://drive.google.com/drive/folders/1BusMWt6ul8QbDb1R-2HBz-Gduc0zJk1D).
- There are 2 types of latest payments: xpay_mpgs, khqr.

## Scope
- [x] Add new ACLEDA preferences fields
  - ACLEDA now supports custom name and logo
- [x] Add new field when create session
  - For xpay_mpgs payment
    - other_url (return url)
    - payment_card (0: pay with visa, master, 1: acleda account)
  - For khqr, when create session: (WIP)
    - operation_type: 3 (ACLEDA only support "3")
- [x] Fix db read-only mode

image

### Related PR
- cm-market-client: https://github.com/bookmebus-backend/cm-market-client/pull/136
- cm-market-app:
  - https://github.com/bookmebus-backend/cm-market-app/pull/950
  - https://github.com/bookmebus-backend/cm-market-app/pull/968

### CODE REVIEW

**Comment by theachoem** [comment]
# Current integratino state

## 1. Tested and work
Current is only work for XPAY.
| | |
| - | - |
| telegram-cloud-photo-size-5-6077833668707072545-y | telegram-cloud-photo-size-5-6077833668707072546-y |

## 2. Not work yet, required support from ACLEDA
a. Pay with cards not working
b. KHQR not render, and we don't have app to scan.

| | |
| - | - |
| telegram-cloud-photo-size-5-6077833668707072543-y |  telegram-cloud-photo-size-5-6077833668707072544-y |

**Comment by channainfo** [comment]
@theachoem looks great, let's put the screenshots/instructions in the README under the docs folder.

**Comment by theachoem** [comment]
| XPAY | Card | KHQR |
| - | - | - |
| Screenshot_1705478598 | Screenshot_1705478641 | Screenshot_1705478613 |

**Comment by channainfo** [comment]
@theachoem let's resize the logo app/assets/images/vpago/payway/product_logo.png smaller. The size should be at most 2x of the display size. It would be great if we could extract the logo out of the spree_vpago with config instead because this gem should not know about bookme plus. plus instead, it should be used for any company.

**Pull request merged**
